import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '@/src/_app/styles/globals.css'
import { MainProvider } from '@/src/shared/providers'

const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`${montserrat.variable} antialiased transition-colors `}
				suppressHydrationWarning
			>
				<MainProvider>
					<div className='relative flex min-h-screen flex-col'>
						<div className='flex min-h-screen flex-col items-center space-y-10'>
							{children}
						</div>
					</div>
				</MainProvider>
			</body>
		</html>
	)
}
